Refactor read operations
talha252/fp2018_bonus2 pull request #2
Opened 2018-04-11 21:08 UTC by cobang

2018-04-12 16:12 UTC, talha252 commented on Main.hs
> +                          return ([validateAndConvertCard line] ++ rest) where
Rather than concatenating two lists, we could use `:` operator as 
`validateAndConvertCard line:rest`
since this is essentially adding an element to a list.

2018-04-12 16:12 UTC, talha252 commented on Main.hs
> +                          return ([validateAndConvertMove line] ++ rest) where
same as above applies here as well.

2018-04-12 16:12 UTC, talha252 commented on Main.hs
> +                            validateAndConvertMove :: String -> Move
Again splitting this function into two would simplify this function dramatically.

2018-04-12 16:12 UTC, talha252 commented on Main.hs
> +                            validateAndConvertCard :: String -> Card
When function name becomes long, you can see it as a sign of overcomplicated function. `validateAndConvertCard` is a long name for a function I think. It is a generally good idea to give only one job to a function (it has two jobs now). So maybe we should split this function into two functions: `validate` and `convertCard`. Luckily, we already have `convertCard` function :) and the job of `validate` function should be returning right characters for good inputs or raising an error for bad inputs. Then, we can use two functions as `(convertCard . validate)` which is a better solution in my opinion. What do you think?

2018-04-12 16:13 UTC, talha252 commented
Also, I think these changes should be in two commits. Thanks for your hardworking!

2018-04-12 16:22 UTC, gokselcoban commented on Main.hs
> +                            validateAndConvertCard :: String -> Card
I think you are right. Using function composition could be more clear.

2018-04-20 16:25 UTC, talha252 requested changes

2018-04-20 16:25 UTC, talha252 commented on Main.hs
> +                            validate [c1]       = if (c1 == 'd' || c1 == 'D') then (c1, 'x', 'x') else err
We already check the first character for 'Unrecognized Move' in `convertMove` function. I think this function should only check for the number of characters that are entered. So simply:
````
validate :: String -> (Char, Char, Char)
validate [c1]       = (c1, 'x', 'x')
validate [c1,c2,c3] = (c1, c2, c3)
validate _          = 'Invalid string'
````

2018-04-20 16:25 UTC, talha252 commented on Main.hs
> +                          return ((convertMove.validate) line : rest) where
The convention is `convertMove . validate` to make it more clear.

2018-04-20 16:26 UTC, talha252 requested changes

2018-04-20 16:26 UTC, talha252 commented on Main.hs
> +                          return ((convertCard.validate) line : rest) where
The convention is `convertCard . validate`

2018-04-20 16:28 UTC, talha252 commented
I really appreciate your work! Thank you for making the changes. I asked new (little) changes. Hopefully, these are not much headache for you.

2018-04-20 17:47 UTC, talha252 approved these changes

2018-04-20 17:47 UTC, talha252 commented
Looks great! Merging!

2018-04-20 17:47 UTC, merged

2018-04-20 17:52 UTC, cobang commented
Thank you. There is no problem for me. This is a chance to realise my mistakes. I hope more friends contribute to upcoming exercises.